services:
  fiber:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/wope?sslmode=disable
      - PORT=8080
    depends_on:
      db:
        condition: service_healthy
                
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=wope
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "5432:5432"
    