apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbServiceName }}
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: "{{ .Release.Name }}-{{ .Values.serverName }}"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080