apiVersion: apps/v1
kind: Deployment
metadata:
  name: "backend-deployment"
  labels:
    team: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "backend"
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
      - name: backend
        image: arifcelik/fiber-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "postgres://postgres:mypassword@db-service:5432/fiber?sslmode=disable"